---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=8.2.2"
license_file: LICENSE
name: eos
description: Ansible Network Collection for Arista EOS devices.
namespace: arista
readme: README.md
repository: https://github.com/ansible-collections/arista.eos
issues: https://github.com/ansible-collections/arista.eos/issues
tags: [arista, eos, networking, eapi]
build_ignore:
  - .yamllint
  - .prettierignore
  - .pre-commit-config.yaml
  - .isort.cfg
  - .gitignore
  - .flake8
  - .ansible-lint
  - sonar-project.properties
  - .github/
version: 12.0.0
