---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": ">=6.1.0"
license_file: LICENSE
name: eos
description: Ansible Network Collection for Arista EOS devices.
namespace: arista
readme: README.md
repository: https://github.com/ansible-collections/arista.eos
issues: https://github.com/ansible-collections/arista.eos/issues
tags: [arista, eos, networking, eapi]
version: 9.0.0
