---
authors:
  - Ansible Network Community (ansible-network)
dependencies:
  "ansible.netcommon": "*"
license_file: LICENSE
name: eos
description: Ansible Network Collection for Arista EOS devices.
namespace: arista
readme: README.md
repository: https://github.com/ansible-collections/arista.eos
tags: [arista, eos, networking, eapi]
# NOTE(pabelanger): We create an empty version key to keep ansible-galaxy
# happy. We dynamically inject version info based on git information.
version: null
