---
name: Bug Report
description: "🐞 Create a report to help us improve"
body:
  - type: markdown
    attributes:
      value: |
        Bug Report issues are for **concrete, actionable bugs** only.

  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Briefly describe the problem.
    validations:
      required: false

  - type: checkboxes
    id: components
    attributes:
      label: Select the relevant components
      options:
        - label: Module
        - label: Action Plugin
        - label: Connection Plugin (cliconf)
        - label: HTTP API Plugin
        - label: Terminal Plugin
        - label: Module Utils
        - label: Documentation
        - label: Integration Tests
        - label: Unit Tests
        - label: Collection Release
        - label: CI Maintenance
        - label: Workflow Maintenance

  - type: input
    id: eos_version
    attributes:
      label: EOS Version
      description: Version of EOS running on the device (e.g., 4.20.0M, 4.24.0F, 4.28.0F)
      placeholder: 4.x.x
    validations:
      required: false

  - type: input
    id: hardware_platform
    attributes:
      label: Hardware Platform
      description: Hardware platform if applicable (e.g., DCS-7050, DCS-7280, vEOS, cEOS)
      placeholder: DCS-7050 / DCS-7280 / vEOS / cEOS
    validations:
      required: false

  - type: input
    id: module_name
    attributes:
      label: Module/Plugin Name
      description: If applicable, specify the module or plugin name (e.g., eos_config, eos_bgp_global)
      placeholder: eos_xxx
    validations:
      required: false
