---
bugfixes:
    - Fixed an issue in the `compare_configs` method where unnecessary negate commands were generated for ACL entries already present in both `have` and `want` configurations.
    - Improved validation logic for ACL sequence numbers and content matching to ensure idempotency.
    - Prevented redundant configuration updates for Access Control Lists.
